FROM python:3.8

ENV HOME /root
WORKDIR /root

COPY . .

RUN pip install -r requirements.txt

EXPOSE 5000
EXPOSE 27017

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

CMD /wait && python3 -u app.py